#!/usr/bin/env python3
"""
Archive all reviewed images to permanent GitHub Pages storage.

Problem: every image generated by fal.ai lives on fal.media for weeks-to-months,
then gets garbage-collected. Our Gallery references those URLs directly, so when
they expire, the whole curated pile shows broken thumbnails.

Fix: download every image we care about (likes, super-likes, rejects — per
Justin's 2026-04-09 directive "even the rejects if storage is not a constraint")
and push them to jbarad424/ideas/winners/{id}.jpg on GitHub Pages. Also ship
a cb-archived.json manifest so the client can rewrite URLs at render time.

Sources (the 694-item reviewed corpus):
- _rate_corpus.json (local) — id -> url mapping for all 694 reviewed images
- cb-keepers.json (GitHub Pages) — the 217 super/yes curated subset

After running, the client loads cb-archived.json into an ARCHIVED_IDS Set on
init. Any image whose ID is in the set gets its <img src> rewritten to the
archived URL. Everything else still uses the original (may or may not work
depending on fal.media TTL).

Usage:
    cd scripts
    python3 archive_winners.py [--skip-push]

    --skip-push  — download + stage files under /tmp/ideas-archive-staging
                    but don't clone / commit / push. For dry-run testing.
"""
import argparse
import concurrent.futures
import hashlib
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
STAGING = "/tmp/ideas-archive-staging"
WINNERS_DIR = os.path.join(STAGING, "winners")
MANIFEST_PATH = os.path.join(STAGING, "cb-archived.json")
CORPUS_PATH = os.path.join(REPO_ROOT, "_rate_corpus.json")
KEEPERS_URL = "https://jbarad424.github.io/ideas/cb-keepers.json"

GITHUB_PAGES_BASE = "https://jbarad424.github.io/ideas/winners/"

UA = "cb2-archive-bot/1.0 (justin.barad@gmail.com)"


def log(msg):
    print(f"[archive] {msg}", flush=True)


def fetch_keepers():
    """Fetch cb-keepers.json from GitHub Pages — the 217 super/yes curated list."""
    req = urllib.request.Request(KEEPERS_URL + "?t=" + str(int(time.time())), headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def load_corpus():
    """Load the local 694-item reviewed corpus."""
    with open(CORPUS_PATH) as f:
        return json.load(f)


def build_download_list():
    """
    Union all reviewed IDs + URLs from corpus + keepers. Dedupe by id.
    Skip entries that are already on jbarad424.github.io (no need to re-archive).
    Returns: list of {id, url, source, label, model} dicts
    """
    corpus = load_corpus()
    log(f"loaded _rate_corpus.json: {len(corpus)} items")

    by_id = {}
    for it in corpus:
        iid = it.get("id")
        url = it.get("url")
        if not iid or not url:
            continue
        if "jbarad424.github.io" in url:
            continue  # already archived
        by_id[iid] = {
            "id": iid,
            "url": url,
            "source": "corpus",
            "label": it.get("label", ""),
            "model": it.get("model", ""),
        }

    try:
        keepers = fetch_keepers()
        for url, it in keepers.get("items", {}).items():
            iid = it.get("id")
            if not iid:
                # Synthesize a stable id from the URL hash for items missing one
                iid = "kp-" + hashlib.sha1(url.encode()).hexdigest()[:12]
            if iid in by_id:
                continue
            if "jbarad424.github.io" in url:
                continue
            by_id[iid] = {
                "id": iid,
                "url": url,
                "source": "keepers",
                "label": it.get("label", ""),
                "model": it.get("model", ""),
            }
        log(f"merged cb-keepers.json: now {len(by_id)} unique items")
    except Exception as e:
        log(f"WARN: could not fetch cb-keepers.json ({e}) — continuing with corpus only")

    return list(by_id.values())


def safe_filename(iid):
    """Return a filesystem-safe filename for an id. IDs are already reasonable."""
    # IDs in the corpus are things like "act-ski-7001", "refab-p2-mtb-s1",
    # "mm-abc-12345" — all safe. Fall back to hash if an ID has weird chars.
    if all(c.isalnum() or c in "-_" for c in iid):
        return iid + ".jpg"
    return "h-" + hashlib.sha1(iid.encode()).hexdigest()[:12] + ".jpg"


def download_one(item, winners_dir):
    """Download one image to winners_dir. Returns (id, status, size_bytes_or_err)."""
    fname = safe_filename(item["id"])
    out_path = os.path.join(winners_dir, fname)
    if os.path.exists(out_path) and os.path.getsize(out_path) > 10000:
        return (item["id"], "cached", os.path.getsize(out_path))
    try:
        req = urllib.request.Request(item["url"], headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=60) as r:
            data = r.read()
            # Quick sanity: must be image bytes (JPEG starts with FFD8, PNG with 89504E47)
            if not (data.startswith(b"\xff\xd8") or data.startswith(b"\x89PNG")):
                return (item["id"], "bad_format", f"not jpg/png, first bytes: {data[:8].hex()}")
            with open(out_path, "wb") as f:
                f.write(data)
        return (item["id"], "ok", len(data))
    except urllib.error.HTTPError as e:
        return (item["id"], "http_error", f"{e.code} {e.reason}")
    except Exception as e:
        return (item["id"], "error", str(e)[:120])


def build_manifest(items, winners_dir):
    """
    Scan what's actually on disk and build cb-archived.json.
    Format: {"meta": {...}, "ids": ["id1", "id2", ...], "items": {"id1": {"url": "...", ...}}}
    """
    archived_ids = []
    items_map = {}
    for item in items:
        fname = safe_filename(item["id"])
        fpath = os.path.join(winners_dir, fname)
        if os.path.exists(fpath) and os.path.getsize(fpath) > 10000:
            archived_ids.append(item["id"])
            items_map[item["id"]] = {
                "filename": fname,
                "url": GITHUB_PAGES_BASE + fname,
                "original": item["url"],
                "source": item["source"],
            }
    return {
        "meta": {
            "generated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "count": len(archived_ids),
            "note": "Archived from fal.media / catbox.moe to permanent GitHub Pages storage.",
        },
        "ids": sorted(archived_ids),
        "items": items_map,
    }


def push_via_git(winners_dir, manifest_path):
    """Clone jbarad424/ideas, copy winners/ + manifest into it, commit, push."""
    clone_dir = "/tmp/ideas-archive-push"
    if os.path.exists(clone_dir):
        subprocess.run(["rm", "-rf", clone_dir], check=True)
    log(f"cloning jbarad424/ideas (shallow) to {clone_dir}")
    subprocess.run(["gh", "repo", "clone", "jbarad424/ideas", clone_dir, "--", "--depth", "1"], check=True)

    target_winners = os.path.join(clone_dir, "winners")
    os.makedirs(target_winners, exist_ok=True)
    # rsync the winners dir (only new files)
    log("copying winners/ into clone")
    subprocess.run(["rsync", "-a", winners_dir + "/", target_winners + "/"], check=True)
    # Copy manifest
    subprocess.run(["cp", manifest_path, os.path.join(clone_dir, "cb-archived.json")], check=True)

    log("git add + commit")
    subprocess.run(["git", "-C", clone_dir, "add", "winners/", "cb-archived.json"], check=True)
    # Count new files staged
    staged = subprocess.run(
        ["git", "-C", clone_dir, "diff", "--cached", "--name-only"],
        capture_output=True, text=True, check=True,
    ).stdout.strip().splitlines()
    log(f"staged {len(staged)} files")
    if not staged:
        log("nothing to push (all files already up to date)")
        return
    msg = f"Archive: {len([s for s in staged if s.startswith('winners/')])} images permanently preserved on Pages"
    subprocess.run(
        ["git", "-C", clone_dir,
         "-c", "user.email=justinbarad@users.noreply.github.com",
         "-c", "user.name=Justin Barad",
         "commit", "-m", msg],
        check=True,
    )
    log("git push")
    subprocess.run(["git", "-C", clone_dir, "push"], check=True)
    log("PUSHED")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-push", action="store_true", help="stage files but don't git push")
    parser.add_argument("--limit", type=int, default=0, help="only process first N items (for testing)")
    parser.add_argument("--workers", type=int, default=16)
    args = parser.parse_args()

    os.makedirs(WINNERS_DIR, exist_ok=True)

    items = build_download_list()
    log(f"{len(items)} items to consider")
    if args.limit:
        items = items[: args.limit]
        log(f"--limit: processing {len(items)}")

    if not items:
        log("nothing to do")
        return

    log(f"downloading with {args.workers} workers…")
    t0 = time.time()
    results = {"ok": 0, "cached": 0, "bad_format": 0, "http_error": 0, "error": 0}
    fail_details = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as ex:
        futures = [ex.submit(download_one, it, WINNERS_DIR) for it in items]
        for i, f in enumerate(concurrent.futures.as_completed(futures), 1):
            iid, status, detail = f.result()
            results[status] = results.get(status, 0) + 1
            if status not in ("ok", "cached"):
                fail_details.append((iid, status, detail))
            if i % 25 == 0:
                log(f"progress {i}/{len(items)} — ok={results['ok']} cached={results['cached']} fail={len(fail_details)}")
    dt = time.time() - t0

    log(f"done in {dt:.1f}s: {json.dumps(results)}")
    if fail_details:
        log(f"FAILURES ({len(fail_details)}):")
        for iid, status, detail in fail_details[:20]:
            log(f"  {iid}: {status} — {detail}")
        if len(fail_details) > 20:
            log(f"  … and {len(fail_details) - 20} more")

    # Size check
    total_bytes = sum(os.path.getsize(os.path.join(WINNERS_DIR, f))
                      for f in os.listdir(WINNERS_DIR))
    log(f"winners dir: {total_bytes / 1_000_000:.1f} MB across {len(os.listdir(WINNERS_DIR))} files")

    manifest = build_manifest(items, WINNERS_DIR)
    with open(MANIFEST_PATH, "w") as f:
        json.dump(manifest, f, indent=2)
    log(f"manifest: {len(manifest['ids'])} archived, written to {MANIFEST_PATH}")

    if args.skip_push:
        log("--skip-push set, stopping here")
        return

    push_via_git(WINNERS_DIR, MANIFEST_PATH)
    log("archive complete — manifest at https://jbarad424.github.io/ideas/cb-archived.json")


if __name__ == "__main__":
    main()
