#!/usr/bin/env python3
"""
Archive all reviewed images to permanent GitHub Pages storage.

Problem: every image generated by fal.ai lives on fal.media for weeks-to-months,
then gets garbage-collected. Our Gallery references those URLs directly, so when
they expire, the whole curated pile shows broken thumbnails.

Fix: download every image we care about (likes, super-likes, rejects — per
Justin's 2026-04-09 directive "even the rejects if storage is not a constraint")
and push them to jbarad424/ideas/winners/{id}.jpg on GitHub Pages. Also ship
a cb-archived.json manifest so the client can rewrite URLs at render time.

Sources (the 694-item reviewed corpus):
- _rate_corpus.json (local) — id -> url mapping for all 694 reviewed images
- cb-keepers.json (GitHub Pages) — the 217 super/yes curated subset

After running, the client loads cb-archived.json into an ARCHIVED_IDS Set on
init. Any image whose ID is in the set gets its <img src> rewritten to the
archived URL. Everything else still uses the original (may or may not work
depending on fal.media TTL).

Usage:
    cd scripts
    python3 archive_winners.py [--skip-push]

    --skip-push  — download + stage files under /tmp/ideas-archive-staging
                    but don't clone / commit / push. For dry-run testing.
"""
import argparse
import concurrent.futures
import hashlib
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
STAGING = "/tmp/ideas-archive-staging"
WINNERS_DIR = os.path.join(STAGING, "winners")
VIDEOS_DIR = os.path.join(WINNERS_DIR, "videos")
MANIFEST_PATH = os.path.join(STAGING, "cb-archived.json")
CORPUS_PATH = os.path.join(REPO_ROOT, "_rate_corpus.json")
CB_REVIEW_PATH = os.path.join(REPO_ROOT, "cb-review.html")
KEEPERS_URL = "https://jbarad424.github.io/ideas/cb-keepers.json"

GITHUB_PAGES_BASE = "https://jbarad424.github.io/ideas/winners/"
GITHUB_PAGES_VIDEOS_BASE = "https://jbarad424.github.io/ideas/winners/videos/"

UA = "cb2-archive-bot/1.0 (justin.barad@gmail.com)"


def log(msg):
    print(f"[archive] {msg}", flush=True)


def fetch_keepers():
    """Fetch cb-keepers.json from GitHub Pages — the 217 super/yes curated list."""
    req = urllib.request.Request(KEEPERS_URL + "?t=" + str(int(time.time())), headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def load_corpus():
    """Load the local 694-item reviewed corpus."""
    with open(CORPUS_PATH) as f:
        return json.load(f)


def load_videos_from_html():
    """
    Extract the ALL_VIDEOS array from cb-review.html. The array is a JS object
    literal so we can't json.loads it directly — instead we walk each {...}
    block and pull out id/url/model/label fields with regex. Brittle if anyone
    rewrites the format, but bounded by the bracket-balance check below.
    """
    if not os.path.exists(CB_REVIEW_PATH):
        log("WARN: cb-review.html not found, skipping videos")
        return []
    with open(CB_REVIEW_PATH) as f:
        html = f.read()
    import re
    m = re.search(r'const ALL_VIDEOS\s*=\s*\[(.*?)\n\];', html, re.DOTALL)
    if not m:
        log("WARN: ALL_VIDEOS array not found in cb-review.html")
        return []
    block = m.group(1)
    videos = []
    # Match each {id:'...', url:'...', model:'...', ...} object
    for entry in re.finditer(r"\{[^{}]*?\}", block):
        text = entry.group(0)
        id_m = re.search(r"id:\s*'([^']+)'", text)
        url_m = re.search(r"url:\s*'([^']+)'", text)
        if not (id_m and url_m):
            continue
        model_m = re.search(r"model:\s*'([^']*)'", text)
        label_m = re.search(r"label:\s*'([^']*)'", text)
        videos.append({
            "id": id_m.group(1),
            "url": url_m.group(1),
            "source": "all_videos",
            "model": model_m.group(1) if model_m else "",
            "label": label_m.group(1) if label_m else "",
        })
    log(f"loaded {len(videos)} videos from cb-review.html ALL_VIDEOS")
    return videos


def build_download_list():
    """
    Union all reviewed IDs + URLs from corpus + keepers. Dedupe by id.
    Skip entries that are already on jbarad424.github.io (no need to re-archive).
    Returns: list of {id, url, source, label, model} dicts
    """
    corpus = load_corpus()
    log(f"loaded _rate_corpus.json: {len(corpus)} items")

    by_id = {}
    for it in corpus:
        iid = it.get("id")
        url = it.get("url")
        if not iid or not url:
            continue
        if "jbarad424.github.io" in url:
            continue  # already archived
        by_id[iid] = {
            "id": iid,
            "url": url,
            "source": "corpus",
            "label": it.get("label", ""),
            "model": it.get("model", ""),
        }

    try:
        keepers = fetch_keepers()
        for url, it in keepers.get("items", {}).items():
            iid = it.get("id")
            if not iid:
                # Synthesize a stable id from the URL hash for items missing one
                iid = "kp-" + hashlib.sha1(url.encode()).hexdigest()[:12]
            if iid in by_id:
                continue
            if "jbarad424.github.io" in url:
                continue
            by_id[iid] = {
                "id": iid,
                "url": url,
                "source": "keepers",
                "label": it.get("label", ""),
                "model": it.get("model", ""),
            }
        log(f"merged cb-keepers.json: now {len(by_id)} unique items")
    except Exception as e:
        log(f"WARN: could not fetch cb-keepers.json ({e}) — continuing with corpus only")

    return list(by_id.values())


def safe_filename(iid):
    """Return a filesystem-safe filename for an id. IDs are already reasonable."""
    # IDs in the corpus are things like "act-ski-7001", "refab-p2-mtb-s1",
    # "mm-abc-12345" — all safe. Fall back to hash if an ID has weird chars.
    if all(c.isalnum() or c in "-_" for c in iid):
        return iid + ".jpg"
    return "h-" + hashlib.sha1(iid.encode()).hexdigest()[:12] + ".jpg"


def download_one(item, winners_dir):
    """Download one image to winners_dir. Returns (id, status, size_bytes_or_err)."""
    fname = safe_filename(item["id"])
    out_path = os.path.join(winners_dir, fname)
    if os.path.exists(out_path) and os.path.getsize(out_path) > 10000:
        return (item["id"], "cached", os.path.getsize(out_path))
    try:
        req = urllib.request.Request(item["url"], headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=60) as r:
            data = r.read()
            # Quick sanity: must be image bytes (JPEG starts with FFD8, PNG with 89504E47)
            if not (data.startswith(b"\xff\xd8") or data.startswith(b"\x89PNG")):
                return (item["id"], "bad_format", f"not jpg/png, first bytes: {data[:8].hex()}")
            with open(out_path, "wb") as f:
                f.write(data)
        return (item["id"], "ok", len(data))
    except urllib.error.HTTPError as e:
        return (item["id"], "http_error", f"{e.code} {e.reason}")
    except Exception as e:
        return (item["id"], "error", str(e)[:120])


def video_filename(iid):
    """Stable .mp4 filename for a video id."""
    if all(c.isalnum() or c in "-_" for c in iid):
        return iid + ".mp4"
    return "h-" + hashlib.sha1(iid.encode()).hexdigest()[:12] + ".mp4"


def download_video(item, videos_dir):
    """
    Download one video to videos_dir/{id}.mp4. Cached if already present.
    Sanity check: ftyp box near the start of an mp4 (or webm magic).
    """
    fname = video_filename(item["id"])
    out_path = os.path.join(videos_dir, fname)
    if os.path.exists(out_path) and os.path.getsize(out_path) > 50000:
        return (item["id"], "cached", os.path.getsize(out_path))
    try:
        req = urllib.request.Request(item["url"], headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=120) as r:
            data = r.read()
            # MP4: 'ftyp' box at offset 4. WebM: starts with 1A 45 DF A3.
            head = data[:32]
            is_mp4 = b"ftyp" in head[:32]
            is_webm = data.startswith(b"\x1a\x45\xdf\xa3")
            if not (is_mp4 or is_webm):
                return (item["id"], "bad_format", f"not mp4/webm, first 32: {head.hex()}")
            with open(out_path, "wb") as f:
                f.write(data)
        return (item["id"], "ok", len(data))
    except urllib.error.HTTPError as e:
        return (item["id"], "http_error", f"{e.code} {e.reason}")
    except Exception as e:
        return (item["id"], "error", str(e)[:120])


def build_manifest(items, winners_dir, videos=None, videos_dir=None):
    """
    Scan what's actually on disk and build cb-archived.json.
    Format: {
      "meta": {...},
      "ids":        ["photo_id1", ...],   # photos archived
      "items":      {"id": {url, filename, ...}, ...},  # photos
      "video_ids":  ["video_id1", ...],   # videos archived
      "videos":     {"id": {url, filename, ...}, ...},  # videos
    }
    """
    archived_ids = []
    items_map = {}
    for item in items:
        fname = safe_filename(item["id"])
        fpath = os.path.join(winners_dir, fname)
        if os.path.exists(fpath) and os.path.getsize(fpath) > 10000:
            archived_ids.append(item["id"])
            items_map[item["id"]] = {
                "filename": fname,
                "url": GITHUB_PAGES_BASE + fname,
                "original": item["url"],
                "source": item["source"],
            }
    archived_video_ids = []
    videos_map = {}
    for v in (videos or []):
        fname = video_filename(v["id"])
        fpath = os.path.join(videos_dir or "", fname)
        if videos_dir and os.path.exists(fpath) and os.path.getsize(fpath) > 50000:
            archived_video_ids.append(v["id"])
            videos_map[v["id"]] = {
                "filename": fname,
                "url": GITHUB_PAGES_VIDEOS_BASE + fname,
                "original": v["url"],
                "source": v.get("source", "all_videos"),
                "model": v.get("model", ""),
                "label": v.get("label", ""),
            }
    return {
        "meta": {
            "generated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "count": len(archived_ids),
            "video_count": len(archived_video_ids),
            "note": "Archived from fal.media / catbox.moe to permanent GitHub Pages storage. Photos under /winners/, videos under /winners/videos/.",
        },
        "ids": sorted(archived_ids),
        "items": items_map,
        "video_ids": sorted(archived_video_ids),
        "videos": videos_map,
    }


def push_via_git(winners_dir, manifest_path):
    """Clone jbarad424/ideas, copy winners/ + manifest into it, commit, push."""
    clone_dir = "/tmp/ideas-archive-push"
    if os.path.exists(clone_dir):
        subprocess.run(["rm", "-rf", clone_dir], check=True)
    log(f"cloning jbarad424/ideas (shallow) to {clone_dir}")
    subprocess.run(["gh", "repo", "clone", "jbarad424/ideas", clone_dir, "--", "--depth", "1"], check=True)

    target_winners = os.path.join(clone_dir, "winners")
    os.makedirs(target_winners, exist_ok=True)
    # rsync the winners dir (only new files)
    log("copying winners/ into clone")
    subprocess.run(["rsync", "-a", winners_dir + "/", target_winners + "/"], check=True)
    # Copy manifest
    subprocess.run(["cp", manifest_path, os.path.join(clone_dir, "cb-archived.json")], check=True)

    log("git add + commit")
    subprocess.run(["git", "-C", clone_dir, "add", "winners/", "cb-archived.json"], check=True)
    # Count new files staged
    staged = subprocess.run(
        ["git", "-C", clone_dir, "diff", "--cached", "--name-only"],
        capture_output=True, text=True, check=True,
    ).stdout.strip().splitlines()
    log(f"staged {len(staged)} files")
    if not staged:
        log("nothing to push (all files already up to date)")
        return
    msg = f"Archive: {len([s for s in staged if s.startswith('winners/')])} images permanently preserved on Pages"
    subprocess.run(
        ["git", "-C", clone_dir,
         "-c", "user.email=justinbarad@users.noreply.github.com",
         "-c", "user.name=Justin Barad",
         "commit", "-m", msg],
        check=True,
    )
    log("git push")
    subprocess.run(["git", "-C", clone_dir, "push"], check=True)
    log("PUSHED")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-push", action="store_true", help="stage files but don't git push")
    parser.add_argument("--limit", type=int, default=0, help="only process first N items (for testing)")
    parser.add_argument("--workers", type=int, default=16)
    parser.add_argument("--skip-photos", action="store_true", help="skip the photo download step (manifest still scans /winners/ on disk)")
    parser.add_argument("--skip-videos", action="store_true", help="skip the video download step (manifest still scans /winners/videos/ on disk)")
    parser.add_argument("--force-shrink", action="store_true", help="bypass the safety guard that refuses to push a smaller manifest than what's live")
    args = parser.parse_args()

    os.makedirs(WINNERS_DIR, exist_ok=True)
    os.makedirs(VIDEOS_DIR, exist_ok=True)

    # Always build the full lists — they're cheap and the manifest needs them
    # to enumerate everything that's already on disk. The --skip flags only
    # control whether we re-download. If we ALSO zeroed out the lists here,
    # build_manifest would emit an empty {ids:[],items:{}} block and silently
    # wipe the live cb-archived.json on push (the --skip-photos regression
    # that nuked 693 entries on 2026-04-09).
    items = build_download_list()
    videos = load_videos_from_html()

    if args.limit:
        items = items[: args.limit]
        videos = videos[: args.limit]
        log(f"--limit: processing {len(items)} photos + {len(videos)} videos")

    # === PHOTOS ===
    if items and not args.skip_photos:
        log(f"PHOTOS: downloading {len(items)} with {args.workers} workers…")
        t0 = time.time()
        results = {"ok": 0, "cached": 0, "bad_format": 0, "http_error": 0, "error": 0}
        fail_details = []
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as ex:
            futures = [ex.submit(download_one, it, WINNERS_DIR) for it in items]
            for i, f in enumerate(concurrent.futures.as_completed(futures), 1):
                iid, status, detail = f.result()
                results[status] = results.get(status, 0) + 1
                if status not in ("ok", "cached"):
                    fail_details.append((iid, status, detail))
                if i % 50 == 0:
                    log(f"  photos {i}/{len(items)} — ok={results['ok']} cached={results['cached']} fail={len(fail_details)}")
        log(f"  photos done in {time.time()-t0:.1f}s: {json.dumps(results)}")
        if fail_details:
            log(f"  PHOTO FAILURES ({len(fail_details)}):")
            for iid, status, detail in fail_details[:10]:
                log(f"    {iid}: {status} — {detail}")

    # === VIDEOS ===
    if videos and not args.skip_videos:
        log(f"VIDEOS: downloading {len(videos)} with {min(args.workers, 8)} workers…")
        t0 = time.time()
        v_results = {"ok": 0, "cached": 0, "bad_format": 0, "http_error": 0, "error": 0}
        v_fail = []
        with concurrent.futures.ThreadPoolExecutor(max_workers=min(args.workers, 8)) as ex:
            futures = [ex.submit(download_video, v, VIDEOS_DIR) for v in videos]
            for i, f in enumerate(concurrent.futures.as_completed(futures), 1):
                vid, status, detail = f.result()
                v_results[status] = v_results.get(status, 0) + 1
                if status not in ("ok", "cached"):
                    v_fail.append((vid, status, detail))
                log(f"  video {i}/{len(videos)} — {vid}: {status}")
        log(f"  videos done in {time.time()-t0:.1f}s: {json.dumps(v_results)}")
        if v_fail:
            log(f"  VIDEO FAILURES ({len(v_fail)}):")
            for vid, status, detail in v_fail:
                log(f"    {vid}: {status} — {detail}")

    # Size summary
    if os.path.exists(WINNERS_DIR):
        photo_files = [f for f in os.listdir(WINNERS_DIR) if not os.path.isdir(os.path.join(WINNERS_DIR, f))]
        photo_bytes = sum(os.path.getsize(os.path.join(WINNERS_DIR, f)) for f in photo_files)
        log(f"winners/: {photo_bytes / 1_000_000:.1f} MB across {len(photo_files)} files")
    if os.path.exists(VIDEOS_DIR):
        video_files = os.listdir(VIDEOS_DIR)
        video_bytes = sum(os.path.getsize(os.path.join(VIDEOS_DIR, f)) for f in video_files)
        log(f"winners/videos/: {video_bytes / 1_000_000:.1f} MB across {len(video_files)} files")

    manifest = build_manifest(items, WINNERS_DIR, videos=videos, videos_dir=VIDEOS_DIR)
    with open(MANIFEST_PATH, "w") as f:
        json.dump(manifest, f, indent=2)
    log(f"manifest: {len(manifest['ids'])} photos + {len(manifest['video_ids'])} videos archived, written to {MANIFEST_PATH}")

    # Safety guard — refuse to push if the new manifest has FEWER photos or
    # videos than the live one. This prevents bug-class regressions like the
    # 2026-04-09 --skip-photos wipe (which silently dropped 693 entries to 0).
    try:
        live_url = "https://jbarad424.github.io/ideas/cb-archived.json?t=" + str(int(time.time()))
        with urllib.request.urlopen(urllib.request.Request(live_url, headers={"User-Agent": UA}), timeout=20) as r:
            live = json.loads(r.read())
        live_photos = len(live.get("ids", []))
        live_videos = len(live.get("video_ids", []))
        new_photos = len(manifest["ids"])
        new_videos = len(manifest["video_ids"])
        if new_photos < live_photos or new_videos < live_videos:
            log(f"REFUSING TO PUSH: manifest would shrink (live: {live_photos}p+{live_videos}v → new: {new_photos}p+{new_videos}v)")
            log("Re-run without skip flags or use --force-shrink to override.")
            if not getattr(args, "force_shrink", False):
                sys.exit(2)
    except urllib.error.URLError as e:
        log(f"warning: couldn't fetch live manifest for safety check ({e}), proceeding")
    except Exception as e:
        log(f"warning: live manifest check failed ({e}), proceeding")

    if args.skip_push:
        log("--skip-push set, stopping here")
        return

    push_via_git(WINNERS_DIR, MANIFEST_PATH)
    log("archive complete — manifest at https://jbarad424.github.io/ideas/cb-archived.json")


if __name__ == "__main__":
    main()
